name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
        env:
          SPRING_AI_OPENAI_API-KEY: ${{ secrets.OPENAI_API_KEY }}
          SPRING_AI_OPENAI_BASE-URL: ${{ secrets.OPENAI_BASE_URL }}
      - run: ./gradlew build --no-daemon --info