name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-unit-tests-on-different-os:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'macos-latest', 'windows-latest', 'ubuntu-latest' ]
        java: [ '17' ]

    permissions:
      contents: read

    name: Use ${{ matrix.os }} with Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build with Gradle Wrapper On ${{ matrix.os }}
        env:
          SPRING_AI_OPENAI_API_KEY: ${{ vars.OPENAI_API_KEY }}
          SPRING_AI_OPENAI_BASE_URL: ${{ vars.OPENAI_BASE_URL }}
        run: ./gradlew clean build --no-daemon --info